### ISSUE TITLE
Adding Cache Hints for deeply nested fields such as Relay

### ISSUE THREAD

**Issue by intellix** [apollographql/apollo-cache-control-js#14]
So earlier I was fighting with getting my first cache working on a whole root connection which is quite heavy. After fighting and ripping out my hair for a couple of hours with: "Batched=1; Cached=0" with no hint as to why it just wouldn't cache them, I found that disabling engine gave me insight as to why it was not:

```
"cacheControl": {
  "version": 1,
  "hints": [
    {
      "path": [
        "items"
      ],
      "maxAge": 90
    },
    {
      "path": [
        "items",
        "edges"
      ],
      "maxAge": 0
    },
    {
      "path": [
        "items",
        "edges",
        0,
        "node"
      ],
      "maxAge": 0
    }
  ]
}
```

Has there been any thought into the caching of relay compliant fields? The library I'm using in particular uses the helpers from `graphql-relay` for creating it's types: https://github.com/graphql/graphql-relay-js/blob/master/src/connection/connection.js#L110

The only way I can get my relay root field cached is to add a cache hint at every level of the way down to my node. Another problem is that they don't allow you to provide a resolver for things like PageInfo, so you ask for that and suddenly the whole thing is uncacheable again.

Is there a way or do you plan on having other ways to mark whole trees or relay trees to be cacheable? Right now it feels like the only way to get around this is to recreate the whole chain of helper libraries just to add some cache hints.

Example query of which I would like cached:
```
{
  items(first: 1) {
    edges {
      node {
        id
      }
    }
  }
}
```

When I set a cache-hint on items, it'd be nice for it to reach the `node` field but I'm not sure how the API would allow it. If I could get ahold of the CacheControlExtension class and add hints manually I think I could workaround it

Engine only allows me to set caching to either: **true** or **false** but I was thinking I could get away with a custom cache extension to do it by inheriting maxAge when the type is an Edge or PageInfo

Potential options I see:
 - Extend CacheExtension to increase flexibility
 - Allow specifying a custom cache extension with Engine
 - Fork graphql-relay and other libraries to support passing resolvers to paginator/edges
 - Document a way to add cache hints to children/parents if they exist perhaps? dunno if possible

**Comment by glasser** [comment]
Even without Relay this is easy to run into; eg, if you have a resolver with `@cacheControl` that calculates an interesting nested piece of data and relies on default resolvers, then you'll still get the maxAge 0 for nested data.

Maybe there should be a `@cacheControl(maxAge: 'inherit')`? 

Maybe default resolvers should act that way automatically?

**Comment by glasser** [comment]
If nothing else this needs to be better documented.

**Comment by jamiehill** [comment]
Agreed, I'd mistakenly assumed the directive would percolate down and apply to the entire ast.  If setting a `maxAge` on a top level type, why would you not want it to apply to all nested types by default?

**Comment by martijnwalraven** [comment]
@jamiehill 

> If setting a maxAge on a top level type, why would you not want it to apply to all nested types by default?

The issue is that the schema defines a graph, so types by themselves don't really have a notion of nesting. Nesting only makes sense for particular queries, and having query nesting decide the cache policy would mean that different paths to the same object would result in different cacheability.

Take the following schema:

```graphql
type Query {
  post(id: ID!): Post
  user(id: ID!): User
}

type Post {
  id: ID!
  title: String
  author: User
}

type User @cacheControl(maxAge: 3600) {
  id: ID!
  name: String
  authored: [Post]
}
```

It seems weird to me that this query wouldn't be cacheable:

```graphql
query {
  post(id: 1) {
    title
    author {
      name
    }
  }
}
```

But this query would be cacheable for an hour, even if it includes the exact same objects:

```graphql
query {
  user(id: 1) {
    name
    authored {
      title
    }
  }
}
```

Maybe that is ok, but it's not immediately clear to me that it is the right thing to do. I like the idea of including a way to inherit cache control hints though. It makes a lot of sense for objects that 'belong to' a parent object, less sure about independent objects.

**Comment by jakubriedl** [comment]
We ran into the same issue where caching is defined on parent entity and so we expected all child entities without their own config will follow the parent one.

To do that we did a little workaround in formatResponse to copy all the config to children. https://gist.github.com/jakubriedl/7085a43ff6793348fafb0e15ee803658

**Comment by evans** [comment]
Let's move discussion over to apollographql/apollo-server#1295, since this repo will be archived now that it's in apollo-server with apollographql/apollo-server#1294
