### ISSUE TITLE
Idea: Reduce all hints into a top-level "maxAge"

### ISSUE THREAD

**Issue by ThisIsMissEm** [apollographql/apollo-cache-control-js#17]
We have all the hints for each path available, giving that path's max-age. It'd potentially be a nice idea to have an overall "max-age" hint, which would simply be the reduction of all hints into the lowest value for maxAge (i.e., the maxAge for the entire query is the minimum maxAge for any path of the query).

This could then be used/leveraged to send correct cache-control headers.

**Comment by evans** [comment]
@ThisIsMissEm Thank you for the issue! We've implemented this in AS2, apollographql/apollo-server#1138 🎉

You're also able to specify a default maxAge for the entire schema as a configuration option to `cacheControl` parameter in the ApolloServer constructor
