### ISSUE TITLE
TS2459 on GraphQLResolveInfo

### ISSUE THREAD

**Issue by rportugal** [apollographql/apollo-cache-control-js#6]
I'm getting an error when trying to use `cacheControl` in a resolver like this:
```
resolve: (parentValue, { id, format }, { models }, { cacheControl })
```

Error:
```
server/graphql/schema/root_query.ts (89,60): Type 'GraphQLResolveInfo' has no property 'cacheControl' and no string index signature. (2459)
```

Since the `GraphQLResolveInfo` interface is redeclared in `apollo-cache-control-js/src/index.ts`, this seems to fix it:
```
import * as apolloCacheControl from "apollo-cache-control";
```

I'm not sure if this the best approach to use the new interface 😄 

Thanks

**Comment by martijnwalraven** [comment]
I think that is the way to go, but you don't need to `import * as apolloCacheControl`, this should be enough:

```
import 'apollo-cache-control';
```
