### ISSUE TITLE
Question on implementing a caching gateway

### ISSUE THREAD

**Issue by albertorestifo** [apollographql/apollo-cache-control-js#8]
First of all, thanks for the amazing work and tooling you've been providing to the community, they're a game-changer.

I'm trying to create a GraphQL gateway which stitches some sachema together and implements caching in a fashion described in the talk ["The GraphQL stack: How everything fits together"][1], but I'm not sure I'm approaching the problem the right way, and if possible I would appreciate some hints.

I've been trying to implement the gateway by using `graphql-tools/makeRemoteExecutableSchema` and a custom link:

1. The servers that the gateway stitches all use `apollo-server` to return cache-control information
1. The gateway stores the results in a datastore (redis/memcached) according to the cache control extensions
1. A custom `link` passed to the `makeRemoteExecutableSchema` disassembles the operations by checking every node of the operation against the cache. If there is an hit, that node is removed from the operation
1. The remaining operation continues to the `apollo-link-http`
1. The result of the http link is hydrated with the cache hit

Am I over engineering this and missing an easier approach? Is there any tool to walk and mutate the operation document (point 3)?

[1]: https://dev-blog.apollodata.com/the-graphql-stack-how-everything-fits-together-35f8bf34f841

**Comment by albertorestifo** [comment]
Nope @Nighthawk14 , I haven't gone forward with the project so far. 

I can only answer this question:

> Is there any tool to walk and mutate the operation document (point 3)?

I used the [`visit`](https://graphql.org/graphql-js/language/#visit) method from the GraphQL.js language functions. It works great for parsing GraphQL AST.

**Comment by evans** [comment]
GraphQL directives work great for walking over an AST as well. You can read about them here https://www.apollographql.com/docs/apollo-server/v2/features/creating-directives.html

I'm going to close the issue, since this repo is moving into apollo-server https://github.com/apollographql/apollo-server/
